apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: mainapp-svc
spec:
  type: ClusterIP
  selector:
    app: mainapp
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
