apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
        - name: dwk-secrets
          image: ahojukka5/dwk-secrets:latest
          env:
            - name: SECRET1
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: mysecret1
            - name: SECRET2
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: mysecret2
