apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    MONGO_PASSWORD: AgCeM3hOcqGmlrBxlNe0NMrEVxlTVE0jpGtEWvYSX0E9eBicGaqeP+ocBDjlMubeuJ+W+N5HtFAkQAbuylOdIeHvOOywPduyP+42mxoLOPZFF1FS3e+wcTNn/dzz/mSMjZvi+C/e/45d3svmXaL36F+FOdNTE+KjJoYp9+6N+q5Bcj9nAVPxw7AqK6TZXA7UtdWgwmXtqyKzGV8HtkNm82LoS7/U3/Y0XlQ6E5ScLNKXOq8ZNpfemXI8O8m4ghN+uDers9AjAFu2judhfLmfOEuAgM5bZRYb4jhPbqRDzqEy2CEMXYVTuNtX2W1YJgiH+XQmXxqhhVCRK8ea+ubB7DHjOrvd7tUSzMuKeQHbGiQS83ewETy4KLcQ682d615k8KFPWVDVfs8LOdxnnRzh8Ss/Z7Tc+loI1ky/Yx/vQ7vjTwtEASTcksgfBp+4UMl7jPrFSUO48VvqXnHr+qHhlv2loiqqngAPr7zDHaQGpcimJbgFR/XvvjTnjZt0j8kW4/9zMbEOgr0ePb4uLF+EXmqMZ0+BEYEcGN2HfXY1ZZ1apMeITW51s+vsSh6yToI88U06POD3NPi1l+glHcFivdmapJ6ipXLqNHzSXH2IAGfDDwZmA/okaqhDC2P8RGOjeNRC9pgX1uOY8jVwMO0Z02znCkikbYK0UhYEorKW1B9V4SurcaBWN3UquZIorTvK4eWV75eJhiE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo

