apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: dwk-main-gen-timestamp
          image: ahojukka5/dwk-main-gen-timestamp:0.2
          volumeMounts:
            - name: cache
              mountPath: /cache
        - name: dwk-main-read-timestamp
          image: ahojukka5/dwk-main-read-timestamp:0.5
          volumeMounts:
            - name: cache
              mountPath: /cache
